import { defineConfig, type Plugin } from "vite";
import react from "@vitejs/plugin-react";
import tailwind from "@tailwindcss/vite";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const MARK = resolve(__dirname, "../../docs/assets/mark-stack.svg");
/** The one workspace version (root package.json is the truth — see
 *  scripts/version.mjs). The landing prints it, so a reader can tell which
 *  squinch the site describes without opening the CLI. */
const VERSION: string = JSON.parse(readFileSync(resolve(__dirname, "../../package.json"), "utf8")).version;

/** Inlines the layered mark into any page carrying `<!--mark-stack-->`.
 *
 *  Inlined rather than referenced because the landing animates the mark's
 *  individual planes, and page CSS cannot reach inside an img — nor does an
 *  img-embedded SVG get pointer events or the reader's motion preference.
 *  Inlining keeps the motion in site.css beside the rest of the landing's, and
 *  leaves docs/assets/mark-stack.svg a plain drawing for the consumers that
 *  want a picture (the README, og.png, the hero GIF's watermark).
 *
 *  Substituting via a function, not a string: SVG path data is full of `$`,
 *  which String.replace would read as a replacement pattern. */
const inlineMark = (): Plugin => ({
  name: "squinch-inline-mark",
  transformIndexHtml: {
    order: "pre",
    handler: (html) =>
      html
        .replace("<!--mark-stack-->", () =>
          readFileSync(MARK, "utf8").replace(/^<\?xml[^>]*\?>\s*/, "").trim(),
        )
        .replaceAll("<!--version-->", () => VERSION),
  },
  // the asset is generated by scripts/mark-stack.mts, outside Vite's graph —
  // without this, editing it leaves the dev server showing the old mark
  configureServer(server) {
    server.watcher.add(MARK);
    server.watcher.on("change", (f) => {
      if (f === MARK) server.ws.send({ type: "full-reload" });
    });
  },
});

// The playground is fully static: no server, no telemetry, sources never leave
// the browser (share links carry them in the URL fragment).
export default defineConfig({
  // GitHub Pages serves project sites under /<repo>/, so the deploy workflow
  // passes BASE_PATH from actions/configure-pages. Local dev and the e2e
  // build stay at "/". Runtime pack fetches are already relative
  // (src/squinch.ts), so only the bundle URLs need this.
  base: process.env.BASE_PATH || "/",
  plugins: [react(), tailwind(), inlineMark()],
  // AWS icons are served as static files and fetched on demand per diagram.
  publicDir: resolve(__dirname, "public"),
  server: { port: 5180, strictPort: true },
  build: {
    target: "es2022",
    // One app, four documents: the site pages are static HTML and the
    // playground is the only JS route. Each entry lands in dist/ at its
    // source path, so the Pages upload (apps/spa/dist) needs no change.
    rollupOptions: {
      input: {
        index: resolve(__dirname, "index.html"),
        install: resolve(__dirname, "install/index.html"),
        // Generated by scripts/sync-lookbook.ts from lookbook/README.md —
        // exists on disk only after the sync step, same as examples.ts.
        lookbook: resolve(__dirname, "lookbook/index.html"),
        playground: resolve(__dirname, "playground/index.html"),
      },
    },
  },
});
