// metrics.json -> a plain TS module, so layout works in browsers too (no fs).
import { readFileSync, writeFileSync } from "node:fs";
const table = JSON.parse(readFileSync("metrics.json", "utf8"));
writeFileSync(
  "src/metrics.generated.ts",
  `// GENERATED by scripts/gen-metrics-module.ts — do not edit.\n` +
    `// Precomputed advance widths (em units) per family/weight. Layout measures\n` +
    `// text against this table and never asks the environment.\n` +
    `export const METRICS: Record<string, Record<string, { advances: Record<string, number>; fallback: number }>> =\n` +
    `  ${JSON.stringify(table)};\n`,
);
console.log("wrote src/metrics.generated.ts");
