// Subsets the bundled faces to the metrics repertoire and emits
// src/fonts.generated.ts (base64 woff2), so every rendered SVG can embed the
// exact face the metrics tables were measured from. Text then renders
// identically everywhere — including GitHub's <img> sandbox — instead of
// falling back to whatever the viewer has installed.
//
// Run: npm run gen-fonts   (build-time only; output is committed)
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import subsetFont from "subset-font";

const require = createRequire(import.meta.url);
const metrics = JSON.parse(readFileSync("metrics.json", "utf8"));

const FILES: Record<string, string> = {
  inter: "@fontsource/inter/files/inter-latin-WEIGHT-normal.woff2",
  caveat: "@fontsource/caveat/files/caveat-latin-WEIGHT-normal.woff2",
};

const out: Record<string, Record<string, string>> = {};
for (const [family, pattern] of Object.entries(FILES)) {
  out[family] = {};
  for (const weight of Object.keys(metrics[family])) {
    const file = require.resolve(pattern.replace("WEIGHT", weight));
    const repertoire = Object.keys(metrics[family][weight].advances).join("");
    const woff2 = await subsetFont(readFileSync(file), repertoire, {
      targetFormat: "woff2",
    });
    out[family][weight] = woff2.toString("base64");
    console.log(`subset ${family} ${weight}: ${woff2.length} bytes (${repertoire.length} chars)`);
  }
}

writeFileSync(
  "src/fonts.generated.ts",
  `// GENERATED by scripts/gen-fonts.ts — do not edit.\n` +
    `// Bundled faces subset to the metrics repertoire, woff2, base64. Embedded\n` +
    `// in every rendered SVG via @font-face so text matches the precomputed\n` +
    `// metrics everywhere (non-negotiable: rendering never depends on\n` +
    `// installed fonts). inter → light/dark; caveat → sketch themes.\n` +
    `export const FONTS: Record<"inter" | "caveat", Record<"400" | "500", string>> = ${JSON.stringify(out)};\n`,
);
console.log("wrote src/fonts.generated.ts");
