// Bundle the exported viewer into a committed constant.
//
// The same pattern as `gen-fonts` / `gen-metrics`: the artifact is generated,
// but it is *committed*, so `squinch render -o x.html` never invokes a bundler
// and its output cannot drift when esbuild ships a patch release. Determinism
// is a non-negotiable, and "byte-identical unless someone re-runs the
// generator" is the only version of it that survives a dependency bump.
//
//   npx tsx scripts/gen-html-runtime.ts     (run from packages/core)
//
// CI re-runs this and diffs, exactly like the lookbook and the SPA's examples.
import { build } from "esbuild";
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "src", "render", "html", "runtime.generated.ts");

const result = await build({
  entryPoints: [join(here, "..", "src", "render", "html", "runtime.ts")],
  bundle: true,
  minify: true,
  format: "iife",
  target: "es2020",
  write: false,
  legalComments: "none",
});
const js = result.outputFiles[0].text.trim();

writeFileSync(
  out,
  `// GENERATED by scripts/gen-html-runtime.ts from src/render/html/runtime.ts —\n` +
    `// do not edit. Committed so that rendering never runs a bundler and the\n` +
    `// output cannot drift with an esbuild upgrade; CI re-runs the generator and\n` +
    `// diffs. It bundles view/dive.ts and view/navigate.ts, which is what makes\n` +
    `// "the export moves exactly like the playground" true by construction.\n` +
    `export const RUNTIME_JS = ${JSON.stringify(js)};\n`,
);
console.log(`runtime: ${(js.length / 1024).toFixed(1)} KB → ${out.replace(/.*packages\//, "packages/")}`);
