// Bundle the agent skill into a committed CLI constant.
//
// `squinch skill` installs SKILL.md into agent skill directories, and the file
// it writes must be the one the CLI shipped with — version-locked, not fetched,
// not resolved from disk at runtime. A runtime file lookup would break under
// the gauntlet's esbuild bundling (which plants every other asset by hand) and
// would add a path that only fails after publish; a generated constant compiles
// into dist/ and any bundle for free. Same pattern as core's
// `runtime.generated.ts`: generated, but *committed* — CI re-runs this and
// diffs.
//
//   node scripts/gen-skill.mjs     (run from the repo root)
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = join(root, "packages", "skill", "skills", "squinch", "SKILL.md");
const out = join(root, "packages", "cli", "src", "skill.generated.ts");

const md = readFileSync(src, "utf8");

writeFileSync(
  out,
  `// GENERATED by scripts/gen-skill.mjs from packages/skill/skills/squinch/SKILL.md —\n` +
    `// do not edit. Committed so the published CLI (and the gauntlet's bundled one)\n` +
    `// carries the skill it installs with zero runtime file resolution; CI re-runs\n` +
    `// the generator and diffs.\n` +
    `export const SKILL_MD = ${JSON.stringify(md)};\n`,
);
console.log(`skill: ${(md.length / 1024).toFixed(1)} KB → packages/cli/src/skill.generated.ts`);
