// Bundle the agent skill into a committed CLI constant.
//
// `squinch skill` installs the skill directory — SKILL.md and the reference
// files beside it — into agent skill directories, and what it writes must be
// what the CLI shipped with — version-locked, not fetched, not resolved from
// disk at runtime. A runtime file lookup would break under the gauntlet's
// esbuild bundling (which plants every other asset by hand) and would add a
// path that only fails after publish; a generated constant compiles into dist/
// and any bundle for free. Same pattern as core's `runtime.generated.ts`:
// generated, but *committed* — CI re-runs this and diffs.
//
// The skill is a directory, not a file (2026-10): the body stays under the
// size an agent keeps after context compaction, and the lookup material — the
// layout cookbook, the per-pack icon lists — sits one level deep under
// `references/`, read when SKILL.md says to. Every file under the directory
// is bundled, keyed by its posix-relative path, so a new reference file ships
// with no change here.
//
//   node scripts/gen-skill.mjs     (run from the repo root)
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, dirname, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = join(root, "packages", "skill", "skills", "squinch");
const out = join(root, "packages", "cli", "src", "skill.generated.ts");

/** Every file under the skill directory, SKILL.md first and the rest sorted,
 *  so the constant is byte-stable across platforms (readdir order is not). */
function walk(dir) {
  const files = [];
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) files.push(...walk(p));
    else files.push(p);
  }
  return files;
}
const files = walk(src)
  .map((p) => relative(src, p).split(sep).join("/"))
  .sort((a, b) => (a === "SKILL.md" ? -1 : b === "SKILL.md" ? 1 : a.localeCompare(b)));
if (files[0] !== "SKILL.md") throw new Error(`no SKILL.md under ${src}`);

const bundle = Object.fromEntries(files.map((f) => [f, readFileSync(join(src, f), "utf8")]));
const total = Object.values(bundle).reduce((n, s) => n + s.length, 0);

writeFileSync(
  out,
  `// GENERATED by scripts/gen-skill.mjs from packages/skill/skills/squinch/ —\n` +
    `// do not edit. Committed so the published CLI (and the gauntlet's bundled one)\n` +
    `// carries the skill it installs with zero runtime file resolution; CI re-runs\n` +
    `// the generator and diffs. Keyed by path relative to the skill directory,\n` +
    `// posix separators, SKILL.md first.\n` +
    `export const SKILL_FILES: Record<string, string> = ${JSON.stringify(bundle, null, 0)};\n` +
    `export const SKILL_MD = SKILL_FILES["SKILL.md"];\n`,
);
console.log(
  `skill: ${files.length} files, ${(total / 1024).toFixed(1)} KB → packages/cli/src/skill.generated.ts`,
);
